#!/bin/bash
export MY_APP_NAME=docker_container_name
export SERVER_IP=XXX.XXX.XXX.XX
export PARSE_DASHBOARD_NAME="dashboard app name"
export PARSE_SERVER_PORT=XXXX
export PARSE_DASHBOARD_PORT=XXXX

export MY_APP_ID=YOUR_APP_ID
export MY_APP_API_KEY=YOUR_APP_API_KEY
export MY_APP_JS_KEY=YOUR_APP_JS_KEY
export MY_APP_MASTER_KEY=YOUR_APP_MASTER_KEY
export MY_APP_REST_API_KEY=YOUR_APP_REST_API_KEY
export MY_APP_CLIENT_KEY=YOUR_APP_CLIENT_KEY
export USER_NAME=dcam
export USER_PASSWORD=dcam

./deploy.sh